################################################################################
# FILE: /code/INV/InverenceRVisualTools/R/extended_summary.R
# PURPOSE: Extended summaries
################################################################################
#
require(lubridate)


#############################################################################
#' Show Extended Summary for continuous numerical vector
#'
#' @description Internal function used in ExtSummary.
#' The mandatory statistics are mean, sd, length and nu_na, but you can also
#' obtain other statistics such as RMSE, quantiles and frequencies. Quantiles
#' can be defined either explicitly by a vector or by specifying the number of
#' quantiles you want per tail and in the middle. Frequencies will be returned
#' in each interval generated by a vector of cut-off points.
#' In a second register the relative statistics are shown. Metric statistics
#' such as the mean or quantiles are divided by the standard deviation and count
#' statistics by the length.
#'
#' @param x Continuous numeric vector
#' @param title Character. If not blank it will written at first.
#' @param showQtle Character. "","NONE","MIN","MAX","MIN/MAX","INTERNAL","ALL"
#' @param nQtle0 Integer. Number of close to 0 ten negative power quantiles .1, .01, .001, ...
#' @param nQtlem Integer. Number of central equidistant quantiles (3 for quartiles)
#' @param nQtle1 Integer. Number of close to 1 ten negative power quantiles .9, .99, .999, ...
#' @param qp Numeric vector. Explicit vector of required quantiles
#' @param breakValues Numeric vector. Break points of the intervals of the real line at which the frequency is to be measured.
#' @param showPoints Boolean. Indicates whether you want to display the frequency of the exact points, which makes sense for discrete or mixed distributions with non-zero probability at certain points.
#' @param showRelativeStats Boolean. Indicates whether you want to display the second record with relative statistics
#' @param digits Integer. Number of precision digits
#'
#' @return A table of stats.
#'
#' @examples
#' .ExtSummary.cont(x)
.ExtSummary.cont = function(
    x, title="",
    showRMSE=getOption("ExtSummary.showRMSE"),
    showQtle=getOption("ExtSummary.showQtle"),
    nQtle0=getOption("ExtSummary.nQtle0"),
    nQtlem=getOption("ExtSummary.nQtlem"),
    nQtle1=getOption("ExtSummary.nQtle1"),
    qp=NULL,
    breakValues=c(0),
    showPoints=getOption("ExtSummary.showPoints"),
    showRelativeStats = getOption("ExtSummary.showRelativeStats"),
    digits=getOption("ExtSummary.digits"))
###############################################################################
{
  #x = runif(10,-1,1);title=""; showRMSE=FALSE;showQtle="ALL";nQtle0=2;nQtlem=3;nQtle1=2;qp=NULL;breakValues=c();showPoints=TRUE;digits=4
  #x=df$ratio_incl_tra
  #x=data_trfcl$precio_reco_incl;
  #breakValues = c(10,20,33,36,50,60,70);showPoints=FALSE;
  #nQtle0=1;nQtlem=1;nQtle1=1;showQtle="MIN,MAX"
# cat("TRACE .ExtSummary.cont(x:",length(x),", title='",title,"', showRMSE=",showRMSE,", showQtle='",showQtle,"', nQtle0=",nQtle0,", nQtlem=",nQtlem,", nQtle1=",nQtle1,", qp:",length(qp),",  breakValues:",length(breakValues),",showPoints=",showPoints,", showRelativeStats = ",showRelativeStats,", digits=",showRelativeStats,")\n",sep="")
  qtl = c()
  if(is.null(qp)) {
    qp0 = numeric()
    qp1 = numeric()
    qpm = numeric()
    if(showQtle=="ALL") {
      if(nQtle0> 0) qp0 = sort(0.1^(1:nQtle0))
      if(nQtle1> 0) qp1 = sort(1-(0.1^(1:nQtle1)))
      if(nQtlem>=0) qpm = seq(0,1.000001,1/(nQtlem+1))
    } else if(showQtle=="INTERNAL") {
      if(nQtle0> 0) qp0 = sort(0.1^(1:nQtle0))
      if(nQtle1> 0) qp1 = sort(1-(0.1^(1:nQtle1)))
      if(nQtlem>=0) qpm = seq(0.000001,1.000001,0.99999/(nQtlem+1))
    } else {
      if(grepl("MIN",showQtle)) qpm = c(qpm,0)
      if(grepl("MAX",showQtle)) qpm = c(qpm,1)
    }
    qp = sort(c(qp0,qpm,qp1))
  }
  if(length(qp)) {
    qtl = quantile(x,qp,na.rm=TRUE)
    names(qtl) = gsub("^100%$","max",gsub("^0%$","min",names(qtl)))
  }
  st1 = data.frame(
    mean = mean(x,na.rm=TRUE),
    sd = sd(x,na.rm=TRUE))
  if(showRMSE) {
    st1$mae  = mean(abs(x),na.rm=TRUE)
    st1$rmse = sqrt(mean(x^2,na.rm=TRUE))
  }
  st2 = data.frame(
    length = sum(is.na(x) | x>-.Machine$double.xmax),
    nu_na = sum(is.na(x)))
  ncv = length(breakValues)
  cv = list()
  if(ncv) {
    for(k in 1:ncv) {
      #k=1
      if(showPoints) {
        if(k==1) {
          lt = sum(x<breakValues[k],na.rm = TRUE)
          names(lt) = paste0("x<",breakValues[k])
        } else {
          lt = sum(x>breakValues[k-1] & x<breakValues[k],na.rm = TRUE)
          names(lt) = paste0(breakValues[k-1],"<x<",breakValues[k])
        }
      } else {
        if(k==1) {
          lt = sum(x<=breakValues[k],na.rm = TRUE)
          names(lt) = paste0("x<=",breakValues[k])
        } else {
          if(breakValues[k-1] == breakValues[k]) {
            lt = sum(x==breakValues[k],na.rm = TRUE)
            names(lt) = paste0("x=",breakValues[k])
          } else {
            lt = sum(x==breakValues[k],na.rm = TRUE)
            names(lt) = paste0(breakValues[k-1],"<x<=",breakValues[k])
          }
        }
      }
      cv = c(cv, lt)
      if(showPoints) {
        eq = sum(x==breakValues[k],na.rm = TRUE)
        names(eq) = paste0("x=",breakValues[k])
        cv = c(cv, eq)
      }
      if(k==ncv) {
        gt = sum(x>breakValues[k],na.rm = TRUE)
        names(gt) = paste0(breakValues[k],"<x")
        cv = c(cv, gt)
      }
    }
  }
  abs = cbind(st1,st2)
  rel = cbind(st1/st1$sd,st2/st2$length)
  if(ncv) {
    cvn = names(cv)
    cv = as.data.frame(cv)
    colnames(cv) = cvn
    abs = cbind(abs,cv)
    rel = cbind(rel,cv/st2$length)
  }
  if(length(qtl)) {
    qt = t(as.data.frame(qtl))
    abs = cbind(qt, abs)
    rel = cbind(qt/st1$sd,rel)
  }
  if(showRelativeStats) {
    stats = cbind(round(rbind(abs,rel),digits),type=c("abs","rel"))
  } else {
    stats = cbind(round(abs,digits))
  }
  if(title!="") {
    stats = cbind(id=title,stats)
  }
  rownames(stats)=NULL
  return(stats)
}

#############################################################################
#' Show Extended Summary for discrete numerical vector
#'
#' @description Internal function used in ExtSummary
#'
#' @param x discrete vector
#' @param title Character. If not blank it will written at first.
#' @param max_discrete_levels Integer. Maximum number of levels or distinct values of a discrete vector to display in its frequency table. If these are integers and the number of levels is greater than this threshold, then it will be treated as a continuous vector. If it is a non-numeric discrete vector, only the standard R summary function shall be used.
#'
#' @return A frequency table.
#'
#' @examples
#' .ExtSummary.disc(x)
.ExtSummary.disc = function(
    x, title="",
    digits=getOption("ExtSummary.digits"),
    nlevels,
    max_discrete_levels=getOption("ExtSummary.max_discrete_levels"))
###############################################################################
{
# cat("TRACE .ExtSummary.disc(x:",length(x),", title='",title,"', nlevels=",nlevels,", max_discrete_levels='",max_discrete_levels,"')\n",sep="")
  results = list(
    summ = summary(x)
  )

  if(nlevels<=max_discrete_levels) {
    tx = sort(table(x,useNA = "always"),decreasing = TRUE)
    results$frequency = data.frame(
      item = names(tx),
      frequence = as.numeric(tx),
      ratio = round(as.numeric(tx)/length(x),digits)
    )
  }
  return(results)
}


#############################################################################
#' Show Extended Summary for discrete numerical vector
#'
#' @description Returns the specified statistics on a numeric vector. If x is
#' a discrete vector, then a frequency table is returned. If x is a continuous
#' vector the result is a combination of quantiles and central and dispersion
#' statistics. If x is a data.frame it returns the extended summary of each
#' column taking into account whether it is a discrete or continuous vector.
#'
#' @param x A vector or data.frame
#' @param title Character. If not blank it will written at first.
#' @param showQtle Character. "","NONE","MIN","MAX","MIN/MAX","INTERNAL","ALL"
#' @param nQtle0 Integer. Number of close to 0 ten negative power quantiles .1, .01, .001, ...
#' @param nQtlem Integer. Number of central equidistant quantiles (3 for quartiles)
#' @param nQtle1 Integer. Number of close to 1 ten negative power quantiles .9, .99, .999, ...
#' @param qp Numeric vector. Explicit vector of required quantiles
#' @param breakValues Numeric vector. Break points of the intervals of the real line at which the frequency is to be measured.
#' @param showPoints Boolean. Indicates whether you want to display the frequency of the exact points, which makes sense for discrete or mixed distributions with non-zero probability at certain points.
#' @param showRelativeStats Boolean. Indicates whether you want to display the second record with relative statistics
#' @param digits Integer. Number of precision digits
#' @param max_discrete_levels Integer. Maximum number of levels or distinct values of a discrete vector to display in its frequency table. If these are integers and the number of levels is greater than this threshold, then it will be treated as a continuous vector. If it is a non-numeric discrete vector, the standard R summary function shall be used.
#'
#' @return A table of stats.
#'
#' @examples
#' ExtSummary(x)
ExtSummary = function(
    x, title="",
    showRMSE=getOption("ExtSummary.showRMSE"),
    showQtle=getOption("ExtSummary.showQtle"),
    nQtle0=getOption("ExtSummary.nQtle0"),
    nQtlem=getOption("ExtSummary.nQtlem"),
    nQtle1=getOption("ExtSummary.nQtle1"),
    qp=NULL,
    breakValues=c(0),
    showPoints=getOption("ExtSummary.showPoints"),
    showRelativeStats = getOption("ExtSummary.showRelativeStats"),
    digits=getOption("ExtSummary.digits"),
    max_discrete_levels = getOption("ExtSummary.max_discrete_levels"))
###############################################################################
{
  # x = data.frame(unif=runif(20,-1,1), normal=runif(20,-1,1));
  # x = data.frame(unif=runif(20,-1,1), normal=runif(20,-1,1), discrete=as.integer(round(runif(20,-1,1))));
  # x = runif(20,-1,1);
  # x = as.integer(round(runif(20,-1,1)));
  # title=""; showRMSE=FALSE;showQtle="ALL";nQtle0=2;nQtlem=3;nQtle1=2;qp=NULL;breakValues=c();showPoints=TRUE;digits=4;showRelativeStats = !is.data.frame(x);max_discrete_levels = 20
# cat("TRACE ExtSummary(x:",class(x),", title='",title,"', showRMSE=",showRMSE,", showQtle='",showQtle,"', nQtle0=",nQtle0,", nQtlem=",nQtlem,", nQtle1=",nQtle1,", qp:",length(qp),",  breakValues:",length(breakValues),",showPoints=",showPoints,", showRelativeStats = ",showRelativeStats,", digits=",showRelativeStats,")\n",sep="")
  if(is.data.frame(x)) {
    continuous = data.frame()
    discrete = list()
    for(j in 1:ncol(x)) {
      es =  ExtSummary(
        x = x[,j],
        title = colnames(x)[j],
        showRMSE = showRMSE,
        showQtle = showQtle,
        nQtle0 = nQtle0,
        nQtlem = nQtlem,
        nQtle1 = nQtle1,
        qp = qp,
        breakValues = breakValues,
        showPoints = showPoints,
        showRelativeStats = showRelativeStats,
        digits = digits,
        max_discrete_levels = max_discrete_levels)
      if(is.data.frame(es)) {
        continuous = rbind(continuous, es)
      } else {
        discrete[[colnames(x)[j]]] = es
      }
    }
    if(length(discrete)==0) {
      results = continuous
    } else if(length(continuous)==0) {
      results = discrete
    } else {
      results = list(
        continuous = continuous,
        discrete = discrete
      )
    }
  } else {
    v=x
    is_num = is.numeric(v)
    if(!is_num) {
      v = factor(v,exclude=NULL)
    }
    if(is.factor(v)) {
      is_continuous = FALSE
      nlevels = nlevels(v)
    } else if(is.integer(v)| is.logical(v)) {
      nlevels = length(unique(v))
      is_continuous = nlevels>max_discrete_levels
      if(!is_continuous) {
        v = as.factor(as.numeric(v))
      }
    } else {
      is_continuous = TRUE
    }
    if(is_continuous) {
      results = .ExtSummary.cont(
        x = x,
        title = title,
        showRMSE = showRMSE,
        showQtle = showQtle,
        nQtle0 = nQtle0,
        nQtlem = nQtlem,
        nQtle1 = nQtle1,
        qp = qp,
        breakValues = breakValues,
        showPoints = showPoints,
        showRelativeStats = showRelativeStats,
        digits = digits)
    } else {
      results = .ExtSummary.disc(
        x = x,
        title = title,
        digits = digits,
        nlevels = nlevels,
        max_discrete_levels = max_discrete_levels)
    }
  }
  return(results)
}
